### ISSUE TITLE
setLocale not working in useEffect

### ISSUE THREAD

**Issue by zitanlin** [FallenMax/a18n#17]
function App() {
  const [language, setLanguage] = useState('');
  useEffect(() => {
    const language = Cookies.get('lang') || getUrlParam('lang') || navigator.language || 'zh';
    a18n.setLocale(language);
    setLanguage(language);
  }, []);
  
  return (<div>……</div>);
}

setLocale not working like above.

**Comment by FallenMax** [comment]
@zitanlin Hi, can you provide a minimal reproducible repo?

Please note that `a18n.setLocale()` & `a18n.addLocaleResource()` only change output of a18n calls like `a18n("someText")`. In order to use new language/translation, you need to ensure your app is re-rendered using texts newly generated by `a18n("someText")`.

For static text (i.e. not re-generated when render), they might be bound to stale translations. See https://github.com/FallenMax/a18n#1-why-is-it-important-to-load-translation-resources-and-specify-a-locale-before--all-other-code-is-run for detail. In these situations, you'll have to window.reload() and set correct language before app code execute.

**Comment by zitanlin** [comment]
@FallenMax    Simple demo：https://github.com/zitanlin/a18n-test.git

I have two problems as follow：
1. switch language in useEffect
2. Dynamically switch languages ​​in the page

**Comment by FallenMax** [comment]
https://github.com/zitanlin/a18n-test/blob/master/src/App.js#L15-L17

```ts
  const changeLanguage = async () => {
    const temp = language === 'zh' ? 'en' : 'zh';
    setLanguage(temp);
    await a18n.setLocale(temp); // moving this line up fixes the problem
    await a18n.setLocale(temp);  // this line is unnecessary, also `await` is not required
  };
````

@zitanlin  Hi, the problem is that `setLanguage` is called before `a18n.setLocale(temp)`, this means that react could re-renders this component BEFORE a18n is set to use new language.
As mentioned in comment, moving `a18n.setLocale(temp)` before `setLanguage` fixes this problem (`await` is not required and should be removed). 

Hope this helps!

**Comment by zitanlin** [comment]
https://github.com/zitanlin/a18n-test.git

`const [language, setLanguage] = useState('zh');
  useEffect(async () => {
    console.log('---- use effect = ', language)
    a18n.setLocale('zh');
  }, []);

  const changeLanguage = async () => {
    console.log('--- language = ', language);
    const temp = language === 'zh' ? 'en' : 'zh';
    a18n.setLocale(temp);
    setLanguage(temp);
  };
`
1. setLocale in useEffect function not working. I setLocale('zh') in useEffect, but not working. for example: 
![image](https://user-images.githubusercontent.com/23631975/123387353-46a10580-d5ca-11eb-8b7d-7893299b59ed.png)

2. it does not switch to expected language at first call changeLanguage function, then it works. You can test it.

**Comment by zitanlin** [comment]
> )

**Comment by zitanlin** [comment]
@FallenMax

**Comment by FallenMax** [comment]
@zitanlin 

a18n is a general i18n library, and it does not know about React or any other UI framework. This means `a18n.setLocale()` alone won't do anything about your app UI. As mentioned in previous comments, you need to trigger app re-render using latest locale after  `a18n.setLocale()`, for latest language to take effect.

**Comment by zitanlin** [comment]
@FallenMax Got it, thank you very much！
